#设置语言
language: node_js  
# 指定需要sudo权限
sudo: false
#设置相应的版本
node_js: 
  - '9'
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
   directories:
       - node_modules    
before_install:
  - npm install -g hexo-cli
#安装hexo及插件
install:
  - npm install   
  - npm install hexo-deployer-git --save
  - npm i -g yuque-hexo
  - npm install --save shelljs
script:
  - yuque-hexo clean
  - yuque-hexo sync
  - hexo clean
  - hexo generate
    #  - hexo deploy

#修改成自己的github用户名
#修改成自己的GitHub邮箱
#GH_token就是在travis中设置的token
after_script:
  - cd ./public
  - git init
  - git config user.name "TomatoFryEggs"   
  - git config user.email "jobin0528@hotmail.com"   
  - git add .
  - git commit -m "update by Travis-CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master   

#只监测这个分支，一有动静就开始构建
branches:
  only:
  - master 
env:
    global:
        - GH_REF: github.com/TomatoFryEggs/tomatofryeggs.github.io.git

